name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: turtlebrowser/get-conan@v1.2
    - name: Install Conan Dependencies
      run: |
        conan profile detect --force
        conan install . --output-folder=build --build=missing

    - name: Configure CMake
      run: cmake --preset conan-release

    - name: Build
      run: cmake --build ${{github.workspace}}/build 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C

